### ISSUE TITLE
打开应用之后只有一个空白界面

### ISSUE THREAD

**Issue by wakaryry** [lzwjava/LZAlbum#3]
打开应用只显示一个空白界面，标题为登陆。还需要在哪里设置啥吗？

**Comment by lzwjava** [comment]
截图看看？改了什么吗？应该就像gif 那样的

**Comment by wakaryry** [comment]
![2015-09-02 5 42 46](https://cloud.githubusercontent.com/assets/7576559/9627925/1ed0e3e6-519a-11e5-8108-5c78a8dff501.png)
没有任何动静。我刚刚下载的，然后pod一下就打开运行。

**Comment by wuxiaohuan18** [comment]
iff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.下载运行报错

**Comment by lzwjava** [comment]
请打开 LZAlbum.xcworkspace

**Comment by HuaZao** [comment]
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `LZAlbum` to `Pods/Target Support Files/Pods/Pods.debug.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.debug.xcconfig` in your build configuration.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `LZAlbum` to `Pods/Target Support Files/Pods/Pods.release.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.release.xcconfig` in your build configuration.

**Comment by HuaZao** [comment]
Pod报警告.打开报错
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by lzwjava** [comment]
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `LZAlbum` to `Pods/Target Support Files/Pods/Pods.debug.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.debug.xcconfig` in your build configuration.
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `LZAlbum` to `Pods/Target Support Files/Pods/Pods.release.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.release.xcconfig` in your build configuration.

这个删除掉 下面图示的文件，再 pod install 一次

![image](https://cloud.githubusercontent.com/assets/5022872/9714183/b950f5d6-5588-11e5-8f62-2acd22a1b906.png)

> Pod报警告.打开报错
> diff: /../Podfile.lock: No such file or directory
> diff: /Manifest.lock: No such file or directory
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

这个请把具体错误界面截图过来看看
